### ISSUE TITLE
Conditional independence notation not support

### ISSUE THREAD

**Issue by dxxzst** [orsharir/github-mathjax#42] opened 2021-07-22 03:31 UTC
https://www.johndcook.com/blog/2020/03/27/conditional-independence-notation/
$\perp\!\!\!\perp$

**Comment by muzimuzhi** [comment] 2021-07-22 04:35
Duplicate of #16. Try `$\perp\\!\\!\\!\perp$` or `$\perp\kern-9mu\perp$`: 

$\perp\\!\\!\\!\perp$ or $\perp\kern-9mu\perp$

**Comment by dxxzst** [comment] 2021-07-22 05:08
@muzimuzhi Thanks
$\perp\kern-9mu\perp$

**Closed as completed** 2021-07-22 05:09 UTC
