### ISSUE TITLE
newline is ignored.

### ISSUE THREAD

**Issue by ghost** [orsharir/github-mathjax#27] opened 2019-03-28 12:17 UTC
It seems that newline(`\\`) is ignored. For example:

```
$$
x\\
x^2
$$
```

Actual:

$$
x\\
x^2
$$

**Comment by jinbeomhong** [comment] 2019-03-28 18:00
$$
x\\
x^2
$$

**Comment by muzimuzhi** [comment] 2019-03-29 03:53
Try
```latex
$$
x \\\\
x^2
$$
```
$$
x \\\\
x^2
$$

BTW, `LaTeX + amsmath` does not support raw newline in display math, unless it is inside some multi-row `amsmath` math environment. But MathJax supports this kind of input, as I have tested on mathjax.org. So personally I suggest to use a `amsmath` env, e.g. `align(ed)`.

**Comment by muzimuzhi** [comment] 2019-04-30 19:18
Also, this issue is duplicate of #26 .

**Comment by jinbeomhong** [comment] 2019-04-30 19:27
@muzimuzhi Thanks. Do i need to close this issue?

**Closed as completed** 2019-04-30 19:28 UTC
