### ISSUE TITLE
`{}` escape problem with the plugin

### ISSUE THREAD

**Issue by david11rsww** [orsharir/github-mathjax#26] opened 2019-03-05 12:30 UTC
When the mathjax expression is `$\{...\}$` format, then the plugin will not render out `{}`. It requests a double escape format `$\\{...\\}$` in order to render out the html content `{}` .

**Comment by ghost** [comment] 2019-04-17 13:47
Duplicate of https://github.com/orsharir/github-mathjax/issues/10 . See this.

```
U=$\lbrace1,2,3\rbrace$
```

$U=\lbrace1,2,3\rbrace$

**Comment by muzimuzhi** [comment] 2019-04-18 11:49
For commands having backslash and single non-letter symbol as its name, e.g. `\{`, `\,`..., it seems the backslash should be escaped. For example, use
```
$\\{a, b\\}$
```
to get
$\\{a, b\\}$.

**Comment by muzimuzhi** [comment] 2019-04-18 12:19
This is a "feature" of GitHub Flavored Markdown (GFM), aka, how GitHub converts markdown to html.

First, GitHub converts every pair of `\ + <symbol>` in markdown into the `<symbol>` in html, where the `<symbol>` is a non-letter symbol. See [Backslash Escapes - GFM Spec](https://github.github.com/gfm/#backslash-escapes).

Then the `github-mathjax` extension uses what GitHub outputs as its input. Hence, for `github-mathjax` to get a `\{`, you need type `\\{` as the input of GitHub.

 - Your input (at the same time, input of GitHub): `\\{`
 - Output of Github (at the same time, input of `github-mathjax`): `\{`(`\\` -> `\`, `{` -> `{`)
 - Output of `github-mathjax`: the left brace math symbol

Since `github-mathjax` can only see what GitHub outputs, this "feature" hardly can repair.

**Comment by ghost** [comment] 2019-04-18 14:34
Which editor are you using? I am using VSCode with [vscode-markdown](https://github.com/yzhang-gh/vscode-markdown) extension. Because this extension doesn't show `\\{` appropriately in a live preview pane, I am typing `\lbrace` instead of `\\{`.

**Comment by muzimuzhi** [comment] 2019-04-18 16:15
> Which editor are you using?

@jinbeomhong 

A program uses markdown text as input and outputs html is called a markdown previewer/engine. Every time you "see" the html version (with a plenty of text styles) of some markdown text, you actually "see" the output of some markdown engine.

Here, the vscode extension implements its own markdown engine, which acts, as you have found out, not the same as the engine used by GitHub. Actually, almost every markdown engine acts a bit different with each other, and most of those engines does not have a detailed specification. To this point, GitHub, with its GFM, does a good job.

Bad news is, I have not find any fully-offline markdown engine which acts 100% the same as the one used by GitHub. For example, try the examples in [Tables (extension) - GFM](https://github.github.com/gfm/#tables-extension-) in your vscode extension.

**Closed as completed** 2019-06-06 13:23 UTC
