### ISSUE TITLE
Matrix display error

### ISSUE THREAD

**Issue by BoobooWei** [orsharir/github-mathjax#29] opened 2019-04-30 09:10 UTC
$$
q^{cur} =
\begin{bmatrix}
1\\
1\\
1\\
1\\
\end{bmatrix}
$$

Should be displayed vertically。
应该竖着显示，而不是横着。

[my github page](https://github.com/BoobooWei/booboo_hadoop/blob/master/01_theory/01_Introduction%20to%20the%20origin%20and%20system%20of%20hadoop.md)

**Comment by muzimuzhi** [comment] 2019-04-30 19:24
Duplicate of #27 and #26 .

In general, to get a `\\` in mathjax, you should type in `\\\\`. Due to what character following the newline symbol, it is sometimes enough to use triple `\`, rather than quartic.

**Comment by BoobooWei** [comment] 2019-05-05 06:54
$$
q^{cur} =
\begin{bmatrix}
1\\\\
1\\\\
1\\\\
1\\\\
\end{bmatrix}
$$

Thanks！
谢谢🙏

**Closed as completed** 2019-05-05 06:54 UTC
